app/cf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("jobs.urls", namespace="jobs")),
    path("providers", include("providers.urls", namespace="providers")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/jobs/urls.py
from django.urls import path

from . import views

app_name = "jobs"

urlpatterns = [
    path("", views.JobListView.as_view(), name="list-view"),
]

app/providers/urls.py
from django.urls import path

from . import views

app_name = "providers"

urlpatterns = [
    path("", views.ProviderListView.as_view(), name="provider-list"),
    path("detail/<int:pk>/", views.ProvideDetailView.as_view(), name="provider-detail"),
    path("update/<int:pk>/", views.ProviderUpdateView.as_view(), name="provider-update"),
]

app/jobs/models.py
from django.db import models
from providers.models import District, Provider

ENTRY_LEVEL = "entry level"
MID_LEVEL = "mid level"
SENIOR_LEVEL = "senior level"

SKILL_LEVEL_LIST = [
    (ENTRY_LEVEL, "E"),
    (MID_LEVEL, "M"),
    (SENIOR_LEVEL, "S"),
]


class Tag(models.Model):
    tag = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f"{self.tag} {self.pk}"


class SkillLevel(models.Model):
    skill_level = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f"{self.skill_level} {self.pk}"


class Job(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    posted_by = models.ForeignKey(Provider, on_delete=models.CASCADE)
    skill_level = models.ForeignKey(
        SkillLevel, on_delete=models.SET_DEFAULT, default=2
    )
    hourly_rate = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    posted = models.DateTimeField(auto_now_add=True)
    location = models.ForeignKey(
        District, on_delete=models.SET_NULL, null=True, blank=True
    )
    postal_code = models.CharField(
        max_length=8, help_text="eg: LC03 101", null=True, blank=True
    )
    tags = models.ManyToManyField(Tag)
    likes = models.BooleanField(default=False)
    dislikes = models.BooleanField(default=False)

    def __str__(self):
        return self.name

app/providers/models.py
from django.db import models
from django.urls import reverse


class Provider(models.Model):
    title = models.CharField(max_length=6)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    middle_initial = models.CharField(max_length=1)

    def get_absolute_url(self):
        return reverse("providers:provider-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.title} {self.first_name} {self.middle_initial}. {self.last_name} ({self.pk})"


class District(models.Model):
    district_name = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.district_name} ({self.pk})"


class Address(models.Model):
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    address1 = models.CharField(max_length=255)
    address2 = models.CharField(max_length=255, blank=True, null=True)
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    postal_code = models.CharField(
        max_length=8,
        help_text="<em><a target='_blank' href='https://stluciapostal.com/postal-codes-2/'>Post Codes</a></em>",
    )

    def __str__(self):
        return f"{self.provider} address"


class Contact(models.Model):
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    tel1 = models.CharField(max_length=50)
    tel2 = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField("alternative email, if any?", blank=True, null=True)

    def __str__(self):
        return f"{self.provider} contact"


class OtherDetail(models.Model):
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    driver_license = models.BooleanField(
        "Do you have a current driving license?", default=False
    )
    transport = models.BooleanField("Do you have transport?", default=False)
    language = models.BooleanField("Do you speak any foreign languages?", default=False)
    languages = models.TextField(blank=True)

    def __str__(self):
        return f"{self.provider} ({self.driver_license})"


class Education(models.Model):
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    course = models.CharField(max_length=100, null=True)
    date = models.DateField(blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.course}, {self.date}"


class Relationship(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self) -> str:
        return self.name


class NextOfKin(models.Model):
    provider = models.ForeignKey(Provider, on_delete=models.SET_NULL, null=True)
    nok_name = models.CharField(max_length=200)
    nok_address = models.ForeignKey("Address", on_delete=models.SET_NULL, null=True)
    nok_contact = models.ForeignKey("Contact", on_delete=models.SET_NULL, null=True)
    relationship = models.ForeignKey(
        "Relationship", on_delete=models.SET_NULL, null=True
    )

    def __str__(self) -> str:
        return f"{self.provider}'s KON {self.nok_name}"


class WorkType(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Shift(models.Model):
    name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class WorkSchedule(models.Model):
    name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class WorkInterest(models.Model):
    provider = models.ForeignKey(Provider, on_delete=models.SET_NULL, null=True)
    work_type = models.ManyToManyField(WorkType)
    preferred_shift = models.ManyToManyField(Shift)
    other_commitments = models.BooleanField(
        "Do you have other commitments?", default=False
    )
    work_schedule = models.ForeignKey(
        WorkSchedule, on_delete=models.SET_NULL, null=True
    )

    def __str__(self) -> str:
        return f"{self.provider} work interest {self.work_type.values_list()}"


class Vaccination(models.Model):
    name = models.CharField(max_length=50, unique=True)
    
    def __str__(self):
        return self.name


class ImmunisationStatement(models.Model):
    provider = models.ForeignKey(Provider, on_delete=models.SET_NULL, null=True)
    vaccination = models.ForeignKey(Vaccination, on_delete=models.SET_NULL, null=True)
    i_date = models.DateField("injection date", blank=True, null=True)
    b_date = models.DateField("booster due", blank=True, null=True)

 

    def __str__(self):
        return f"{self.provider} vaccinations"

app/jobs/views.py
from django.views.generic import ListView

from .models import Job


class JobListView(ListView):
    model = Job

app/providers/views.py
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from .models import Provider


class ProviderListView(ListView):
    model = Provider


class ProvideDetailView(DetailView):
    model = Provider


class ProviderUpdateView(UpdateView):
    model = Provider
    fields = "__all__"

app/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous">

    <!-- <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"> -->

    <link rel="stylesheet"
        href="https://fonts.sandbox.google.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

    <link rel="preconnect"
        href="https://fonts.googleapis.com">
    <link rel="preconnect"
        href="https://fonts.gstatic.com"
        crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
        rel="stylesheet">

    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <style>
        html,
        body {
            font-family: 'Montserrat', sans-serif;
        }
    </style>

    <title>

        {% block head_title %}

        {% endblock head_title %}

    </title>

</head>

<body>
    {% include 'header.html' %}

    {% block content %}

    {% endblock content %}


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

app/templates/header.html
<div class="bg-dark">
    <div class="container py-0 d-flex">
        <a class="text-decoration-none text-white mx-2 text-end"
            href="tel:17584568522">1-758-456-8522</a>
        <a class="text-decoration-none text-white mx-2 text-end"
            href="mailto:mail-us@mail.com">email us</a>
    </div>
    <div class="container-fluid d-flex py-2">
        <a class="btn btn-outline-light mx-1" href="/">Home</a>
        <!-- <a class="btn btn-outline-light mx-1" href="/providers">Jobs</a> -->
        <a class="btn btn-outline-light mx-1" href="{% url 'providers:provider-list' %}">Providers</a>
    </div>
</div>

app/templates/jobs/job_list.html
{% extends 'base.html' %}

{% load humanize %}

{% block head_title %}
Jobs
{% endblock head_title %}


{% block content %}
<div class="container py-5">
    <h1>Jobs ({{object_list.count}})</h1>
    <hr>
    <div class="col-lg-4 col-md-8 col-sm-12 mx-auto">
        <input class="form-control rounded-pill"
            type="text" autofocus>
    </div>
    <div class="container py-5">
        <div class="card col-lg-8 col-md-6 col-sm-12 mx-auto">
            <ul class="list-group list-group-flush">
                {% for job in object_list %}
                <li class="list-group-item py-3">
                    <a class="text-decoration-none fs-5 text-dark my-3"
                        href="">{{job.name}}</a>
                    <br>
                    <br>
                    <p class="d-flex text-muted"
                        style="font-size: 14px;">skill level:
                        {{job.skill_level}} - hourly rate: ${{job.hourly_rate}}
                        hr
                        - posted: {{job.posted|naturaltime}}</p>
                    <p style="font-size: 14px;">{{job.description}}</p>
                    <p class="d-flex">
                        {% for tag in job.tags.all %}
                        <button
                            class="btn btn-sm btn-secondary mx-1 rounded-pill">{{tag|title}}</button>
                        {% endfor %}
                    </p>
                    <a href="jobs/{{job.location.district_name}}">
                        <p class="d-flex text-dark fw-bold float-end"><span
                                class="material-symbols-outlined">
                                location_on
                            </span><span
                                style="font-size: 14px;">{{job.location.district_name|title}}</span>
                        </p>
                    </a>
                </li>
                {% empty %}
                <p class="text-center pb-3 pt-4">No Jobs</p>
                {% endfor %}
            </ul>

        </div>
    </div>
</div>

{% endblock content %}

app/templates/providers/provider_detail.html
{% extends 'base.html' %}

{% block head_title %}
{{object}}
{% endblock head_title %}


{% block content %}
<div class="container py-5">
    <h1>{{object}}</h1>
    <hr>
    <div class="container py-5">
        <div class="card bg-info w-50">
            <h3 class="card-header py-4">{{object.first_name}}
                {{object.last_name}}</h3>
            <div class="mx-auto card bg-dark w-100">
                <div class="card-body text-white">
                    <div class="card w-50 bg-dark shadow-lg">
                        <div class="card-body">
                            <p class="card-text">
                                {{object.address_set.last.address1}},
                            </p>
                            <p> {{ object.address_set.last.address2 }},</p>
                            <p>{{object.address_set.last.district.district_name}},
                            </p>
                            <p> {{ object.address_set.last.postal_code }}.</p>
                        </div>
                    </div>
                    <hr>
                    <div class="float-end mb-3">
                        <a href="#"
                            class="btn btn-warning">Edit</a>
                        <a href="#"
                            class="btn btn-danger">delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/providers/provider_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_title %}
{{object}}
{% endblock head_title %}


{% block content %}
<div class="container py-5">
    <h1>{{object}}</h1>
    <hr>
    <div class="container py-5">
        <div class="card bg-info w-50">
            <h3 class="card-header py-4">{{object.first_name}}
                {{object.last_name}}</h3>
            <div class="mx-auto card bg-dark w-100">
                <div class="card-body text-white">
                    <div class="card w-50 bg-dark shadow-lg">
                        <div class="card-body">
                            <form action=""
                                method="post">
                                {% csrf_token %}
                                {{form|crispy}}
                        </div>
                    </div>
                    <hr>
                    <div class="float-end mb-3">
                        <a href="{% url 'providers:provider-detail' object.pk %}"
                            class="btn btn-lg btn-primary">Cancel</a>
                        <button type="submit"
                            class="btn btn-sm btn-outline-danger">Save</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/providers/provider_list.html
{% extends 'base.html' %}

{% block head_title %}
Providers
{% endblock head_title %}


{% block content %}
<div class="container py-5">
    <h1>Providers</h1>
    <hr>
    <div class="container py-5">
        <ol>
            {% for provider in object_list %}
            <li><a class="text-decoration-none text-dark" href="{{provider.get_absolute_url}}">{{provider}}</a></li>
            <hr>
            {% endfor %}
        </ol>
    </div>
</div>

{% endblock content %}